---
- name: Run curl command
  hosts: ansiblemaster
  tasks:
    - name: Execute curl command
      command: curl -v -k http://192.168.86.2:32000/livez
      register: curl_output

    - name: Display curl output
      debug:
        var: curl_output.stdout
