- name: Extract API key from kubeconfig
  hosts: ansiblemaster
  tasks:
    - name: Get API key from kubeconfig
      community.kubernetes.k8s_auth_info:
        kubeconfig: /tmp/config
        extract: api_key
      register: api_key_result

    - name: Print API key
      debug:
        var: api_key_result.api_key
