- name: Create namespaces in kubernetes cluster
  hosts: ansiblemaster

  tasks:
  - name: Create namespace in default Kubernetes cluster
    kubernetes.core.k8s:
      name: "kube-system"
      api_version: v1
      kind: Namespace
      state: present
