- hosts: ansiblemaster
  gather_facts: false
  tasks:
   - name: Create a k8s namespace
     kubernetes.core.k8s_auth:
      kubeconfig: '/tmp/config'
      name: kube-system
      api_version: v1
      kind: Namespace
      state: present
      state: present
